//
// MongoDB collection and schema setup for a sample CRUD app
//
// This script creates the initial "items" collection and sets a JSON schema validation
// for demonstration. Run using:
//   $ node init_mongodb.js
//

// PUBLIC_INTERFACE
/**
 * This script connects to the MongoDB instance specified by environment variables,
 * and sets up the "items" collection with a collection validator. For a real app,
 * run this script once during development/deployment to enforce schema.
 */

const { MongoClient } = require('mongodb');
require('dotenv').config({ path: require('path').join(__dirname, 'db_visualizer', 'mongodb.env') });

const MONGODB_URL = process.env.MONGODB_URL || 'mongodb://appuser:dbuser123@localhost:5000/?authSource=admin';
const MONGODB_DB = process.env.MONGODB_DB || 'myapp';

/**
 * JSON Schema for a sample "items" collection (CRUD target).
 * Adjust as needed for your app.
 */
const itemSchema = {
  bsonType: "object",
  required: ["name", "description", "createdAt"],
  properties: {
    name: {
      bsonType: "string",
      description: "Name of the item (required)"
    },
    description: {
      bsonType: "string",
      description: "Description of the item (required)"
    },
    createdAt: {
      bsonType: "date",
      description: "Creation timestamp (required)"
    },
    updatedAt: {
      bsonType: "date",
      description: "Last update timestamp (optional)"
    }
  }
};

async function setupCollection() {
  /** Connect to MongoDB and ensure the "items" collection exists with desired schema */
  const client = new MongoClient(MONGODB_URL);
  try {
    await client.connect();
    const db = client.db(MONGODB_DB);

    // Drop and recreate collection for demonstration; remove drop in production!
    if ((await db.listCollections({ name: "items" }).toArray()).length) {
      await db.collection("items").drop();
      console.log('Dropped existing "items" collection (demo only).');
    }

    await db.createCollection("items", {
      validator: { $jsonSchema: itemSchema },
      validationLevel: "strict",
      validationAction: "error"
    });

    console.log('Created "items" collection with schema validation.');
  } catch (err) {
    console.error("Error setting up MongoDB collection:", err.message);
    process.exit(1);
  } finally {
    await client.close();
  }
}

if (require.main === module) {
  setupCollection().then(() => {
    console.log("MongoDB initialization completed.");
    process.exit(0);
  });
}

// PUBLIC_INTERFACE
/**
 * Run this script once for initial schema enforcement in your app database.
 * It uses settings from db_visualizer/mongodb.env, which is generated by the startup script.
 */
